export const GET_USER_PENDING = 'GET_USER_PENDING';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAILED = 'GET_USER_FAILED';

export const GET_DETAIL_USER_PENDING = 'GET_DETAIL_USER_PENDING';
export const GET_DETAIL_USER_SUCCESS = 'GET_DETAIL_USER_SUCCESS';
export const GET_DETAIL_USER_FAILED = 'GET_DETAIL_USER_FAILED';

export const GET_DESTINATION_PENDING = 'GET_DESTINATION_PENDING';
export const GET_DESTINATION_SUCCESS = 'GET_DESTINATION_SUCCESS';
export const GET_DESTINATION_FAILED = 'GET_DESTINATION_FAILED';

export const GET_ACTIVITY_PENDING = 'GET_ACTIVITY_PENDING';
export const GET_ACTIVITY_SUCCESS = 'GET_ACTIVITY_SUCCESS';
export const GET_ACTIVITY_FAILED = 'GET_ACTIVITY_FAILED';
